# Generated by Django 3.0.8 on 2020-08-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200803_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
