# Generated by Django 3.0.8 on 2020-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question_num',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
