# Generated by Django 3.0.8 on 2020-08-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_faq_question_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_num',
            field=models.IntegerField(default=0),
        ),
    ]
