# Generated by Django 3.0.8 on 2020-07-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=10),
        ),
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], max_length=10)),
                ('manufacturer', models.TextField()),
                ('model', models.TextField()),
                ('year_of_production', models.IntegerField()),
                ('engine_capacity', models.IntegerField()),
                ('color', models.TextField()),
                ('price', models.FloatField()),
                ('doors', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Category')),
            ],
        ),
    ]
