# Generated by Django 3.0.8 on 2020-07-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200719_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cars',
            name='manufacturer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(max_length=30),
        ),
    ]
