# Generated by Django 3.0.8 on 2020-07-31 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_auto_20200731_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('False', 'OLD')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('new', 'Yes'), ('False', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
        ),
    ]
